apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: file-storage-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile-premium
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: Service
metadata:
  name: volumes-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-shared-storage
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: true
      - name: index-html-producer
        image: nginx:1.14.2
        command: [ 'sh', '-c', 'echo "<p>hello from $HOSTNAME</p>" >> /usr/share/nginx/html/index.html && tail -f /dev/null' ]
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
            readOnly: false
      volumes:
        - name: html
          persistentVolumeClaim:
            claimName: file-storage-claim

