apiVersion: v1
kind: Service
metadata:
  name: volumes-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: html
            mountPath: /usr/share/nginx/html
      volumes:
        - name: html
          azureDisk:
            kind: Managed
            diskName: pv-static-disk
            diskURI: /subscriptions/875759d2-f6a7-4864-a5f3-e230d6c6779c/resourceGroups/MC_fruit-smoothies-rg_fruit-smoothies-6485-aks_eastus/providers/Microsoft.Compute/disks/pv-static-disk
